# Stage 1: Build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"
WORKDIR /src

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore ./api.csproj

# Copy everything else and build
COPY . ./
RUN dotnet build -c Release

ENTRYPOINT ["dotnet", "ef", "database", "update"]
